import React from 'react';
import { StyleProp } from 'react-native';
import { space } from '@/assets';
import { ASColumn } from '@/components';

type Props = React.ComponentProps<typeof ASColumn> & {
  widgetId?: string;
  style?: StyleProp<any>;
  children?: React.ReactNode;
};

/**
 * Auto-generated thin wrapper around ASColumn.
 *
 * Applies the structural props that are constant across every ASColumn
 * instance as overridable defaults, so call sites only declare what varies. This
 * removes the repeated prop blocks SonarQube reports as duplicated code. The
 * rendered element is identical to using ASColumn directly.
 * Generated by the widget-wrapper hoisting pass — do not edit by hand.
 */
const AppColumn: React.FC<Props> = ({ widgetId, ...rest }) => (
  <ASColumn
    spacing={space['2']}
    scrollable={false}
    backgroundImageResizeMode={'contain'}
    scrollDirection={'vertical'}
    name={widgetId}
    testId={widgetId}
    {...rest}
  />
);

export default AppColumn;
