import React from 'react';
import { StyleProp } from 'react-native';
import { color } from '@/assets';
import { ASTextField } from '@/components';

type Props = React.ComponentProps<typeof ASTextField> & {
  widgetId?: string;
  style?: StyleProp<any>;
  children?: React.ReactNode;
};

/**
 * Auto-generated thin wrapper around ASTextField.
 *
 * Applies the structural props that are constant across every ASTextField
 * instance as overridable defaults, so call sites only declare what varies. This
 * removes the repeated prop blocks SonarQube reports as duplicated code. The
 * rendered element is identical to using ASTextField directly.
 * Generated by the widget-wrapper hoisting pass — do not edit by hand.
 */
const AppTextField: React.FC<Props> = ({ widgetId, ...rest }) => (
  <ASTextField
    placeholderTextColor={color.text.tertiary}
    borderActiveColor={color.brand.primary}
    borderErrorColor={color.status.danger}
    autoCapitalize={'none'}
    keyboardType={'default'}
    textFieldType={'custom'}
    allowFontScaling={false}
    autoComplete={'off'}
    maxNumberOfLines={5}
    name={widgetId}
    testId={widgetId}
    {...rest}
  />
);

export default AppTextField;
