import React from 'react';
import { StyleProp } from 'react-native';
import { sharedStyles } from '@/components/shared/sharedStyles';
import { ASText } from '@/components';

type Props = React.ComponentProps<typeof ASText> & {
  widgetId?: string;
  style?: StyleProp<any>;
  children?: React.ReactNode;
};

/**
 * Auto-generated thin wrapper around ASText.
 *
 * Applies the structural props that are constant across every ASText
 * instance as overridable defaults, so call sites only declare what varies. This
 * removes the repeated prop blocks SonarQube reports as duplicated code. The
 * rendered element is identical to using ASText directly.
 * Generated by the widget-wrapper hoisting pass — do not edit by hand.
 */
const AppText: React.FC<Props> = ({ widgetId, ...rest }) => (
  <ASText
    labelType={'string'}
    dragStyle={sharedStyles.textDrag}
    name={widgetId}
    testId={widgetId}
    {...rest}
  />
);

export default AppText;
